language: elixir
elixir:
- 1.8.1
env:
  matrix:
  - secure: OtRPkWALCMTDPtPNOESH2/aIZAq1darHR9v+lCfMmOHSyh/9BKwpUBbeVwPiS3APtRCTCrhpdGf7YVSNPH0FNyKTgplhzB/wJCp2ruIWrzpaaZWrAF9ZiOKGYyoq6tOGYvrKYS5VUdEP3WgGyUddDKLCXIjuysEjuMaR1fStV9ZHNWv/ClvHcCZychyPL0Nk5ORFqdz2Ct7pnHfZNuaCY9FmU3fLRBBY/077xoJYAXriKaiqDT+EcH7zuf1uu4V4BCg+CbjFpkUVxuJeV1LzNiwEcmtdApZAGxtGMNNgDcjZy/CV+e3gTyIM6SrmKdrIVezVJonDp/OJuYTRLRdC7u/ePwnd6AGUt1Z19Aj+7Sswy9AwH+wzAH6gu7Y/lcbqgWJKn3Z6XsLArQ2ImE5SEW6b4t3Rs7SLVWdQfE1j2iYmzNCosd84DvkTM8tHhaXw3QLr95GpmyAIithrvy6b2c0tCFHN2fgmFuh7XnR4VcKWxGPp76UziM3GjAh/zGnxVTlFQ1i3kUzf4zm64fhrF7pJ3Vws2+Dv/clHLhxm5DLeE2uBuditNiGWfgHMCZxzui0Vvnwc/h1ac9WXNo6jlfa38mMV2IVOUWk+lTA5P/BTssGjwO1EpWPZT3h7IoZowuhqCxMLygD1RCVd90OzhX3OTe+B5VwCgM7C+oE43mY=
