language: elixir
elixir:
- 1.4.2
env:
  matrix:
    secure: VPEgRpnvUJZo5lcZgiqR8p5LQDsFZsPxkBYkOfxScBkzZXpoVwC/GelrF9j3QHXO18psKMv41j3IanpSj7x/+nRiD5yyj07DVD4LClPAcXfuhLVHlneBLTeaD2lKuxLQeHOsS1N1hXEHTF5C39hWb5LtUVQ9V2QjtF+9gmAkAOxMzTtnMvDtCFSOk9upUiwEoIu7BzJkpwA5WGBPl5woBBbE7xDYqDW8AWrbvzlVw4bGbkfXOQLbQDsdejyX4IiHlp0eJf24snRcxdtQ9XAvF4TYKCMHNFO13DEtKpxOPRfo4vehuG2EamPF3/P7Km/gbuYOvgMyKYj72Fob6w6ukY2QvU1teM0OHSVfmuhwghCW8O3HqD6NNrkrWR34yUPqTqWnjocn+Crtm87eDXLN/zDY2sVQ5DUc8iGF+0sZYJgRQsI7dtxFtd1Y1nOUBQQ4kvTqABlbdgqhcMkxcI6dMNWb8Lm23PXga2FrFj41m3p7gu1GA5DUL18Pt4hhEePHT5qM0917HlzuHif/8RN31vtAsllup+VwNHdMbPMpyXqRlWM7n+m5UU6hN8YRD7k2dYTTgc0tucoN5kzIMiyd2OjOuJmD2slLmPZoK6eIMMaI3aR8pDpO76ulFAZgO0Zhya4plUC8wohu8HY6v25jZLJD/kesArCyr6zQnGFD5H8=
